---
title: "欢迎你能来。以后有空的话，就听听我的碎碎念吧"
subtitle: "也答应我，倘若内容涉及秘密，那请你保密"
author: "黄逸杰"
date: "from 2024-03-20"
output:
  xaringan::moon_reader:
    css: [default, zh-CN.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
<span style="font-size: 20px;">-------------------------------------------</span> <br>
<span style="font-size: 20px;">我在抄别人的代码，一切都还在学习当中</span> <br>
<span style="font-size: 20px;">我不知道这些代码是什么意思</span> <br>
<span style="font-size: 18px;">render("Feeling and others.Rmd", html_document())</span> <br>
<span style="font-size: 18px;">上面这个代码可以直接复制运行来生成html</span> <br>
<span style="font-size: 18px;">那说说今天吧，我6点半才睡觉，因为突然迷上了网络小短剧。人至少在一定程度上受激素控制，所以也就有了“上瘾”的议题</span> <br>
<span style="font-size: 18px;">早上九点多就醒了，在宿舍是无法睡到中午的，而且对这个阶段的我来说，也绝对是不能睡到中午的。我需要那块敲门砖，我想实现自己的理想，我想做更多自己想做的事情。这句话的颗粒度非常粗糙，它包含着太多太多的内容……</span> <br>
<span style="font-size: 18px;">但每一刻都是最重要的现在，无法反悔就看向未来。祝我自己，拥有与激素对抗的能力</span> <br>
<span style="font-size: 15px;">2024.3.20</span> <br>

---
<span style="font-size: 18px;">胡传鹏老师真的是我很喜欢的老师啊……有能力，有情怀，很活跃，课堂上的瑕疵和不在意的小尴尬反而让我更加喜欢这位老师。在屏幕后面看着大家的畅聊真的心生向往，想和他们一样拥有那样的知识能力，也很好奇当我“成为他们的时候，我又在追求什么呢？”坚定了我一定要考上研的目标了！不是有想读书的心就行，我有自己想“得到”的东西！</span> <br>
<span style="font-size: 15px;">3.20 22：58</span> <br>
---
<span style="font-size: 18px;">今天中午又调试了一下，想做成PPT或者pdf,都遇到了困难，那今天的消遣就先到这吧</span> <br>
<span style="color: red; font-size: 18px;">3.21 开心我的地盘出现了不同的颜色</span> <br>
---
<span style="font-size: 18px;"> I wanna practice my English skill, so I will record my daily in English from now on</span><br>
<span style="font-size: 18px;"> I know my skill is as low as pupil, but it interesting to witness my growth ,right?</span><br>
<span style="font-size: 18px;"> I will use GPT to polish these sentences, it is a way to learning the native  way.</span><br>
<span style="font-size: 18px;"> It is also a way called as predictive learning </span><br>

<span style="color: grey; font-size: 18px;">I want to practice my English skills, so from now on, I will maintain a daily record in English. I understand that my skills are currently at a beginner's level, but it will be interesting to witness my growth, right? I will use GPT to refine these sentences as a step towards mastering the natural flow of the language. This method is also known as predictive learning.——GPT </span><br>
<span style="font-size: 15px;">3.21</span> <br>
---
<span style="font-size: 18px;"> It is surprised that I refreshed myself just after a idea: I should overcome it. It brings me a nice experience in the later. For me, passing the exam is the most important thing over all other things. I need a brick to another stage. </span><br>
<span style="font-size: 18px;"> "I was surprised by how refreshed I felt after simply embracing the idea that I should overcome the challenge. It led to a positive experience subsequently. For me, passing the exam takes precedence over everything else. It's a stepping stone to the next stage." </span><br>
<span style="font-size: 15px;">3.22</span> <br>
---
<span style="font-size: 18px;">终于变成了PPT模式！！！！！！！！也终于解决了上次未完成的任务……爽啊！！！</span> <br>
<span style="font-size: 15px;">test</span> <br>